version: '3.9'

services:
  postgres:
    container_name: basic-postgres
    image: postgres
    env_file:
      postgres.env
    environment:
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
      - rayadonet
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - postgres.env
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped

  schedule-parser:
    container_name: schedule-parser-container
    build: ./schedule-parser
    env_file:
      - services.env
    ports:
      - 5000:5000
    networks:
      - rayadonet
    volumes:
      - schedule-parser-logs:/schedule-parser/logs/
    depends_on:
      - postgres
    restart: unless-stopped

  rest-service:
    container_name: rest-service-container
    build: ./rest-service
    env_file:
      - services.env
    ports:
      - 8000:8000
    networks:
      - rayadonet
    volumes:
      - rest-service-logs:/rest-service/logs/
    depends_on:
      - schedule-parser
    restart: unless-stopped

  vkbot:
    container_name: vkbot-container
    build: ./vkbot
    env_file:
      - vkbot.env
    networks:
      - rayadonet
    volumes:
      - vkbot-logs:/vkbot/logs/
    depends_on:
      - rest-service
    restart: unless-stopped

  tgbot: 
    container_name: tgbot-container
    build: ./tgbot
    env_file:
      - tgbot.env
    networks:
      - rayadonet
    volumes:
      - tgbot-logs:/tgbot/logs/
    depends_on:
      - rest-service
    restart: unless-stopped
  
  logs-service:
    container_name: logs-service-container
    build: ./logs-service
    env_file:
      - logs-service.env
    ports:
      - 9000:9000
    networks:
      - rayadonet
    volumes:
      - schedule-parser-logs:/logs-service/logs/schedule-parser-logs/
      - rest-service-logs:/logs-service/logs/rest-service-logs/
      - vkbot-logs:/logs-service/logs/vkbot-logs/
      - tgbot-logs:/logs-service/logs/tgbot-logs/
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  rayadonet:
    external: true

volumes:
    postgres:
    pgadmin:
    schedule-parser-logs:
    vkbot-logs:
    rest-service-logs:
    tgbot-logs:
